### ISSUE TITLE
GetAccounts no returning all savers when too many savers.

### ISSUE THREAD

**Issue by klunkeh** [jay-oswald/ha-up-bank#4]
When making the call, no page size parameter is being is being passed in, and so if you have too many savers (such as my self), you will inconsistently accounts as some will be on another page.

I have manually changed the python on my side to have ?page[size]=30 which resolves the issue.

I believe that technically you can have 50 savers, plus 50 in the 'recycle bin' for the next month for reporting before they disappear, although I don't know if those would be returned in the call. Then you have the normal spending and 2up spending.

**Comment by jay-oswald** [comment]
Sounds like if the API supports it we should just set page size to 100, way easier to do 1 call than multiple. I'll get around to updating it would just be this line https://github.com/jay-oswald/ha-up-bank/blob/master/custom_components/up/up.py#L30 Unless you want to make the change and put in a PR for it.

I might have to look into how many savers you can have to get a better number, though I highly doubt anyone is using more than 100, even if its technically possible to have more.

**Comment by salty2011** [comment]
Pretty sure I read somewhere it was capped at 50

**Comment by jay-oswald** [comment]
I had completly forgotten about this, but 50 should be more than enough even if its capped at that, I'll test it tonight and update the repo to do a page size of 50

**Comment by jay-oswald** [comment]
@klunkeh @salty2011 
Just pushed up setting page size to 100, I dout anyone could realistically more than that, if they do can update it, if your still having and it is capped at 50 I can look at running multiple pages to get all the data, though I can't read anywhere on the docs page about a cap, so hopefully not an issue. I've tested it on my local dev enviroment, as well as my prod server, its working, but I was under whatever the default was, so not 100% sure it is working
